#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker02"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "68da4ea3e8f54ab8829dca6438a31b26" }
]

[assets]
directory = "./public"
